version: '3.8'

services:
  trader-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trader-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - trader-data:/data
    environment:
      - FLASK_APP=app.py
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
      - FLASK_DEBUG=false
      - PYTHONUNBUFFERED=1
      - DB_PATH=/data/trader.db
      - MAX_RECORD_AGE_DAYS=30
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  trader-data:
    # This named volume will persist the SQLite database between container restarts
